#!/usr/bin/env bash
# Run all 80 test questions against AtlasKB and save results
set -euo pipefail

ATLASKB="$(cd "$(dirname "$0")/.." && pwd)/bin/atlaskb"
OUTFILE="/tmp/atlaskb-test-results.md"

questions=(
  "What services make up the AgentAssist QA platform and what language is each written in?"
  "What is the end-to-end flow of an audio recording from upload to completed transcription?"
  "Which services communicate via AMQP and which use HTTP?"
  "What databases does the platform use and which services connect to each?"
  "How does the system handle encryption and decryption of audio files and transcripts?"
  "What are the main entry points in the vector-transcribe-ui PHP monolith and what does each handle?"
  "How does upload.php process incoming audio files?"
  "What AMQP consumers does the PHP app run and what queues do they listen on?"
  "How does callback.php handle async results from downstream services?"
  "What are the 6 callback endpoint scripts and what does each one process?"
  "How does the intake service achieve high-volume async audio ingestion?"
  "What is the disk durability mechanism in the intake service?"
  "How does intake handle backpressure when downstream services are slow?"
  "What happens if the intake service crashes mid-processing - how is data recovered?"
  "How does the async API differ from the intake service?"
  "What AMQP queues does the async API publish to?"
  "What is the upload flow through the async API?"
  "What speech-to-text engine does the ASR service use?"
  "How does the ASR service handle GPU resource management?"
  "What audio formats does the ASR service accept?"
  "How does Faster-Whisper compare to the standard Whisper model in this deployment?"
  "How does the QA scoring system work end-to-end?"
  "What is the relationship between vector-transcribe-qa and llm-worker?"
  "What LLM inference engine does llm-worker use?"
  "How are QA scorecard prompts structured and evaluated?"
  "How does the QA gateway route requests to the LLM worker?"
  "How does the encryption service implement envelope encryption with AWS KMS?"
  "What is the encrypt/decrypt flow for audio files in vector-encrypt?"
  "How do other services authenticate with the encryption service?"
  "What happens if AWS KMS is unreachable?"
  "How does the postback service deliver transcription results?"
  "What retry logic does postback use for failed deliveries?"
  "What formats can postback deliver results in?"
  "How does the audio API convert recordings to MP3?"
  "What audio processing tools or libraries does vector-transcribe-audio-api use?"
  "What is the full message processing pipeline in the redaction service?"
  "How does the PII detection pipeline work and what PII types does it detect?"
  "How does the redaction service handle word/phrase replacements?"
  "What is the concurrency model in the redaction service - how does it combine asyncio with CPU-bound PII detection?"
  "How does the ProcessPoolExecutor interact with the asyncio event loop in the redaction service?"
  "What happens when the process pool crashes with BrokenProcessPool in the redaction service?"
  "How does the encryption circuit breaker work in the redaction service - what are its thresholds and recovery?"
  "What is the dependency recovery mechanism and how does consumer pausing work in the redaction service?"
  "How does the AMQP connection watchdog detect and recover from stale connections?"
  "What Prometheus metrics does the redaction service expose?"
  "What are the health check endpoints in the redaction service and what does each verify?"
  "How does AWS AppConfig hot-reload work for the redaction service?"
  "Which configuration keys can be changed at runtime vs requiring a drain-and-reconfigure in the redaction service?"
  "What is the reconfigure sequence when an infrastructure key changes in the redaction service?"
  "How does the configuration priority chain work in the redaction service?"
  "What is the INI section-to-field mapping convention in the redaction service?"
  "How is the redaction service deployed with systemd?"
  "What external dependencies does the redaction service require?"
  "How does the redaction service handle audio segment silencing?"
  "What is the recording mover processing pipeline from SQS to intake API?"
  "How does multi-company mode work with dynamic AppConfig reconciliation in the recording mover?"
  "What storage backends does the recording mover support?"
  "How does the mover extract metadata from filenames vs sidecar files vs embedded JSON?"
  "What transform types are available for metadata fields in the recording mover?"
  "How does the Worker Manager reconcile company configurations every 10 minutes?"
  "What SQS message formats does the recording mover support?"
  "How does the streaming multipart upload work via io.Pipe in the recording mover?"
  "What are the normalized metadata fields and how is field resolution ordered in the recording mover?"
  "How does post-processing work in the recording mover?"
  "What are the three test tiers for the recording mover and what does each cover?"
  "How does the mover handle per-region S3 client caching?"
  "How do services discover each other in the AgentAssist platform - is there a service registry or hardcoded URLs?"
  "What is the AMQP queue topology across the AgentAssist platform?"
  "How does the platform handle end-to-end encryption of sensitive audio data?"
  "What monitoring and observability patterns are consistent across the Go services?"
  "How does AWS AppConfig integrate across multiple services in the platform?"
  "What is the deployment strategy - containers, systemd, or both?"
  "How does the platform handle multi-tenant multi-company isolation?"
  "What happens to a recording if the redaction service is down?"
  "What is the error handling philosophy across the platform - retry vs DLQ?"
  "How does the redaction service _pause_for_recovery prevent multiple concurrent recovery loops?"
  "What is the AMQP QOS prefetch strategy and how does it relate to concurrency?"
  "How does the mover handle S3 event notification messages vs native v2 messages differently?"
  "What happens during a hot-reload of the AMQP URL in the redaction service - how are in-flight messages handled?"
  "How does the redaction service throughput stats logging work and what does it report?"
)

echo "# AtlasKB Test Results — $(date '+%Y-%m-%d %H:%M')" > "$OUTFILE"
echo "" >> "$OUTFILE"
echo "80 questions queried against the indexed AgentAssist QA repos." >> "$OUTFILE"
echo "" >> "$OUTFILE"

for i in "${!questions[@]}"; do
  q="${questions[$i]}"
  num=$((i + 1))
  echo "[$num/80] Querying: ${q:0:60}..."

  answer=$($ATLASKB ask "$q" 2>&1) || true

  echo "---" >> "$OUTFILE"
  echo "" >> "$OUTFILE"
  echo "## Q${num}. ${q}" >> "$OUTFILE"
  echo "" >> "$OUTFILE"
  echo '```' >> "$OUTFILE"
  echo "$answer" >> "$OUTFILE"
  echo '```' >> "$OUTFILE"
  echo "" >> "$OUTFILE"
done

echo ""
echo "Done! Results saved to $OUTFILE"
